### ISSUE TITLE
Enhancer incorrectly assumes field already exists

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-api-jpa#34]
The following shows a project that contains various entity mappings but enhancing it fails because a duplicate attribute is said to be encountered. I suppose this is a problem with detecting bridge methods?
[jpa-treat-variations.zip](https://github.com/datanucleus/datanucleus-api-jpa/files/400641/jpa-treat-variations.zip)

**Comment by andyjefferson** [comment]
See https://github.com/datanucleus/datanucleus-core/issues/112 and https://github.com/datanucleus/datanucleus-core/issues/113. The test classes are now processed and enhanced. 

The "model" and "test" do not pass with that since
1. In the TablePerClass case you have relations to classes that are abstract (hence no table, and since you have multiple concrete subclasses then you have no fixed point for a FK column to connect to ... meaning this model will not have FKs as such). This is not supported. 
2. TREAT is supported/tested only under certain inheritance situations in SELECT/WHERE clauses. I have a TODO (and issue) to support it at some point for FROM clauses, but then not something I would use much so low priority.
